public_seating_import:
    resource: "@SeatingBundle/Resources/config/routing/public/_entrypoint.yaml"
    prefix: /
    defaults:
        _format: 'html'

admin_seating_import:
    resource: "@SeatingBundle/Resources/config/routing/admin/_entrypoint.yaml"
    prefix: /admin
    defaults:
        _format: 'html'
