services:
    SeatingBundle\Controller\:
        resource: "%kernel.project_dir%/src/SeatingBundle/Controller/*"
        autowire: true
        autoconfigure: true

    SeatingBundle\Repository\:
        resource: "%kernel.project_dir%/src/SeatingBundle/Repository/*"
        autowire: true
        autoconfigure: true

    SeatingBundle\Command\:
        resource: "%kernel.project_dir%/src/SeatingBundle/Command/*"
        autowire: true
        autoconfigure: true

    SeatingBundle\Form\:
        resource: "%kernel.project_dir%/src/SeatingBundle/Form/*"
        autowire: true
        autoconfigure: true

    SeatingBundle\Serializer\Normalizer\:
        resource: "%kernel.project_dir%/src/SeatingBundle/Serializer/Normalizer/*"
        autowire: true
        autoconfigure: true

    SeatingBundle\Service\:
        resource: "%kernel.project_dir%/src/SeatingBundle/Service/*"
        autowire: true
        autoconfigure: true

    SeatingBundle\Message\:
        resource: "%kernel.project_dir%/src/SeatingBundle/Message/*"
        autowire: true
        autoconfigure: true

    SeatingBundle\MessageHandler\:
        resource: "%kernel.project_dir%/src/SeatingBundle/MessageHandler/*"
        autowire: true
        autoconfigure: true
