seating_event_list:
    path: /event/list
    controller: SeatingBundle\Controller\EventController::listAction
    methods: GET

seating_event_fetch:
    path: /fetchEvents
    controller: SeatingBundle\Controller\EventController::fetchEvents
    methods: GET
