admin_app_homepage_import:
    resource: "@AppBundle/Resources/config/routing/admin/homepage.yaml"
    prefix: /

admin_app_gallery_import:
    resource: "@AppBundle/Resources/config/routing/admin/gallery.yaml"
    prefix: /

admin_app_gallery_item_import:
    resource: "@AppBundle/Resources/config/routing/admin/galleryItem.yaml"
    prefix: /

admin_app_feedback_import:
    resource: "@AppBundle/Resources/config/routing/admin/feedback.yaml"
    prefix: /

admin_app_page_import:
    resource: "@AppBundle/Resources/config/routing/admin/page.yaml"
    prefix: /

admin_app_trojan_import:
    resource: "@AppBundle/Resources/config/routing/admin/trojan.yaml"
    prefix: /
