
admin_app_gallery_list:
    path: /galleries.{_format}
    controller: AppBundle\Controller\GalleryController::listAdminAction
    methods: GET

admin_app_gallery_new:
    path: /galleries/new
    controller: AppBundle\Controller\GalleryController::newAdminAction
    methods: POST

admin_app_gallery_edit:
    path: /galleries/{id}/edit
    controller: AppBundle\Controller\GalleryController::editAdminAction
    methods: PUT
